### ISSUE TITLE
[EXTENSION] Extension Bisect is done and has identified specstory.specstory-vscode as the extension causing the problem.

### ISSUE THREAD

**Issue by baigod** [specstoryai/getspecstory#128]
Extension Bisect is done and has identified specstory.specstory-vscode as the extension causing the problem.

**Comment by belucid** [comment]
Causing what problem @baigod ?

**Comment by baigod** [comment]
<img width="260" height="314" alt="Image" src="https://github.com/user-attachments/assets/4464253b-944b-4d19-b612-50e7fa991560" />

<img width="722" height="216" alt="Image" src="https://github.com/user-attachments/assets/6b466938-dbb5-4fd1-bf86-47dbe2e6bea7" />

<img width="526" height="482" alt="Image" src="https://github.com/user-attachments/assets/c4fd08d0-3625-46d9-a9bc-d41103c1c4e5" />

My cursor will report this error after a while, and finally prompt that there is a problem with the spec story plugin @belucid

**Comment by baigod** [comment]
Here are all my installed plugins
<img width="384" height="840" alt="Image" src="https://github.com/user-attachments/assets/c28def0a-c6c9-47a9-8fdf-e2a47f5a0166" />

**Comment by firstunicorn** [comment]
Same issue. specstory just stopped working exactly 2-3 days ago. Not saving history, make cursor stall and "reset" git to the state of "not initialized", so I can't even commit to Github from GUI without turn off Specstory and reloading cursor.

**Comment by bago2k4** [comment]
hi @firstunicorn and @baigod.
Sorry you are having issues with SpecStory.

Would you please give us the SpecStory output logs.

First enable SpecStory dev-tools so we can see the debug output:
- open settings, from command palette select _Open VSCode settings_ or with _CMD+,_ shortcut
- search for SpecStory
- find and enable _Specstory: **Show Developer Tools**_
- reload the window so the output logs are in debug mode from the beginning

The find the output logs:
- from command palette select _Output: Focus on Output View_
- in the task dropdown (top right corner) select SpecStory (wait for it to be visible if the workspace is still loading)
- copy the full output and send it to us via a GH gist or a text file

Add any information you think it's relevant.
for example the workspace tree structure: is it a single folder or multiple folders? what's the GIT root (where is the .git folder)?

Thanks

**Comment by ihjlyeq** [comment]
I get the same error message, and disabling specstory solves it, also the console continuously reports Git error, please fix this asap.

**Comment by guy-car** [comment]
Hi there - also having this issue. Any solutions / root causes identified?

**Comment by gammatunai-chwy** [comment]
> hi [@firstunicorn](https://github.com/firstunicorn) and [@baigod](https://github.com/baigod). Sorry you are having issues with SpecStory.
> 
> Would you please give us the SpecStory output logs.
> 
> First enable SpecStory dev-tools so we can see the debug output:
> 
> * open settings, from command palette select _Open VSCode settings_ or with _CMD+,_ shortcut
> * search for SpecStory
> * find and enable _Specstory: **Show Developer Tools**_
> * reload the window so the output logs are in debug mode from the beginning
> 
> The find the output logs:
> 
> * from command palette select _Output: Focus on Output View_
> * in the task dropdown (top right corner) select SpecStory (wait for it to be visible if the workspace is still loading)
> * copy the full output and send it to us via a GH gist or a text file
> 
> Add any information you think it's relevant. for example the workspace tree structure: is it a single folder or multiple folders? what's the GIT root (where is the .git folder)?
> 
> Thanks

@bago2k4  I'm having this same issue and when I try to do this, SpecStory seems to be restarting sooo fast it's hard to even get them, but I did manage to after a few attempts. Here's the Gist of what's going on for me. https://gist.github.com/gammatunai-chwy/cd14cd35639a1cc22746b5fe9dbd70ab

**Comment by bago2k4** [comment]
Based on the logs from @gammatunai-chwy and details in this issue, we've implemented a potential fix. The logs suggest SpecStory isn't encountering an error but rather hangs while querying conversations from the Cursor SQLite database. We've released a new version with improvements to this specific query. Could @baigod, @guy-car, and @gammatunai-chwy please install it and test?

I'm keeping this issue open since the fix is somewhat speculative at this point. It may resolve the problem for some of you but not all, as we're not certain everyone is experiencing the same underlying issue.

**Comment by guy-car** [comment]
So far so good over here, thanks guys!

**Comment by firstunicorn** [comment]
For me issue still persist. Git stack on scanning folders: 

<img width="388" height="930" alt="Image" src="https://github.com/user-attachments/assets/53a6c203-4acb-4b43-b3f8-c74766bbeb6c" />

Specstory doesn't save history.
It's only happen for big projects (workspace with a lot of files), fine for smaller. Have literally over 100 extensions and 0 issues with others. This "stall git scanning" happen only when Specstory enabled.

And its all began from one of the update simultaneously with other users

**Comment by firstunicorn** [comment]
> The logs suggest SpecStory isn't encountering an error but rather hangs while querying conversations from the Cursor SQLite database.

If this the case, why it began happen after update simultaneously for many users and fine before? I guess maybe Cursor changed DB structure/architecture?

**Comment by firstunicorn** [comment]
Also, if I run Cursor without Specstory and turn it on AFTER Cursor fully loaded and git scanned - it's working fine (but before even this didn't help).

**Comment by guy-car** [comment]
Hey guys, the issue came back for me. Tried uninstall / reinstall and the extension host crashes multiple times within the first minutes. 
Not sure what's up.

**Comment by bago2k4** [comment]
Hi @baigod , @firstunicorn , @guy-car , @ihjlyeq 

we are happy to announce the release of version 1.0.0 of the SpecStory extension that potentially resolve this problem.

I'm going to close this now, please report any future problem
